<a href="https://colab.research.google.com/github/DanteTHE3rd/Com-labs/blob/main/sep_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **GP 106 Numpy and Matplotlib**

In [ ]:
test1 = [1, 2, 3] # This is a list 
# print(type(test1))

import numpy as np

test2 = np.array(test1) # A numpy array more useful than a list
# print(type(test2))


<class 'list'>
<class 'numpy.ndarray'>


Vectors ==> 1D arrays


In [ ]:
import numpy as np

# Row vector
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.shape) # no of dimentons
print(a.size) # no of elements
print(a[0]) # accesseing the first element


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
5
1


In [ ]:
# Column vector
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(b.shape)
print(b.size)
print(b[0])

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
5
[1]


In [ ]:
# generating vectors
one2ten = np.arange(1, 11 ) 
evenone2ten = np.arange(2,11,2) # menton starting value, end value, step size.
oddone2ten = np.arange(1,11,2)

print(one2ten)
print(evenone2ten)
print(oddone2ten)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[1 3 5 7 9]


In [ ]:
# Generating linear spaced vectors

y = np.linspace(1, 100) # print 50 random numbers between 1 to 100
print(y)
print(y.shape)

x = np.linspace(1, 100, 10) # get 10 no from 1 to 100 in np array
print(x)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
(50,)
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [ ]:
# Matrices ==> 2D arrays

A = np.array([[1, 2, 3], [4, -5, 6], [5, -6 ,7]])
print(A)
print(A.shape)
print(A[1][1]) # 2nd row 2nd column
print(A[0][2]) # 1st row 3rd column

[[ 1  2  3]
 [ 4 -5  6]
 [ 5 -6  7]]
(3, 3)
-5
3


In [ ]:
# generate vectors

v = np.ones(5)
print(v) 
print(type(v[0]))  # *** floating point numbers


w = np.ones(5,  dtype=int)  # *** integer numbers
print(w)

r = np.ones((3, 1), dtype=int) # column vector
print(r)



[1. 1. 1. 1. 1.]
<class 'numpy.float64'>
[1 1 1 1 1]
[[1]
 [1]
 [1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# generate matrices

p = np.ones((2, 3), dtype=int) # 2x3 matrix
# print(p)

q = np.zeros((3,2)) #3x2 martix filled with zeros (float)
# print(q)

print(np.eye(3)) # identity matix

d = np.random.rand(3,2) # matrix filled with radom floats
# print(d)

e = np.random.randint(1,100 , 10) # 10 random numbers from 1 to 100 in a matrix (include 1 and 100)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 7 19 42  3 83 43 42 98 33 70]


In [ ]:
# how to access matices

x = np.array([[1, 2, 3, 4], [6, 7, 8, 9], [10, 11, 12, 13], [14, 15, 16, 17]])
print(x)
print(x[2][3])
print(x[2,3])
print(x[2,:]) # get the 3rd row in a np array
print(x[:,3]) # get the 4th column in a np array


[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
13
13
[10 11 12 13]
<class 'numpy.ndarray'>
